// Add relative image paths below, e.g. "Rat": "assets/animals/rat.png". Empty strings intentionally show nothing.
window.IDLE_HUNTER_IMAGES = {
  "animals": {
    "Rat": "",
    "Mouse": "",
    "Stray Cat": "",
    "Pigeon": "",
    "Crow": "",
    "Rabbit": "",
    "Fox": "",
    "Stray Dog": "",
    "Squirrel": "",
    "Sparrow": "",
    "Deer": "",
    "Wild Boar": "",
    "Wolf": "",
    "Bear": "",
    "Elk": "",
    "Lynx": "",
    "Badger": "",
    "Pheasant": "",
    "Owl": "",
    "Hare": "",
    "Moose": "",
    "Timber Wolf": "",
    "Black Bear": "",
    "Wild Turkey": "",
    "Coyote": "",
    "Raccoon": "",
    "Porcupine": "",
    "Snapping Turtle": "",
    "Grouse": "",
    "Mink": "",
    "Scorpion": "",
    "Sand Viper": "",
    "Vulture": "",
    "Fennec Fox": "",
    "Armadillo": "",
    "Roadrunner": "",
    "Lizard": "",
    "Camel Spider": "",
    "Jerboa": "",
    "Sandstorm Serpent": "",
    "Desert Lion": "",
    "Giant Scorpion": "",
    "Dust Hyena": "",
    "Sand Golem Crab": "",
    "Camel": "",
    "Dune Stalker Wolf": "",
    "Golden Eagle": "",
    "Desert Lynx": "",
    "Mirage Phantom": "",
    "Arctic Wolf": "",
    "Polar Bear": "",
    "Snowy Owl": "",
    "Reindeer": "",
    "Arctic Fox": "",
    "Musk Ox": "",
    "Wolverine": "",
    "Seal": "",
    "Walrus": "",
    "Snow Leopard": "",
    "Jaguar": "",
    "Anaconda": "",
    "Poison Dart Frog": "",
    "Toucan": "",
    "Panther": "",
    "Silverback Gorilla": "",
    "Komodo Dragon": "",
    "Piranha": "",
    "Giant Centipede": "",
    "Alligator": "",
    "Giant Frog": "",
    "Swamp Viper": "",
    "Mudskipper": "",
    "Black Panther": "",
    "Leech Hydra": "",
    "Bog Bear": "",
    "Marsh Hawk": "",
    "Will-o-Wisp Serpent": "",
    "Lava Lizard": "",
    "Magma Boar": "",
    "Ember Wolf": "",
    "Ash Vulture": "",
    "Cinder Crab": "",
    "Obsidian Serpent": "",
    "Flame Lynx": "",
    "Molten Golem": "",
    "Fire Hawk": "",
    "Inferno Bear": "",
    "Skeleton Archer": "",
    "Shadow Wolf": "",
    "Bone Drake": "",
    "Cursed Knight": "",
    "Wraith Stag": "",
    "Plague Rat": "",
    "Stone Golem": "",
    "Phantom Lynx": "",
    "Soul Serpent": "",
    "Ancient Guardian": "",
    "Prismatic Butterfly": "",
    "Chromatic Fox": "",
    "Rainbow Serpent": "",
    "Aurora Deer": "",
    "Spectrum Wolf": "",
    "Iridescent Hawk": "",
    "Prism Panther": "",
    "Hue Shifter Frog": "",
    "Kaleidoscope Crab": "",
    "The Living Rainbow": "",
    "Deep Sea Kraken": "",
    "Abyss Shark": "",
    "Shadow Eel": "",
    "Void Manta": "",
    "Leviathan Crab": "",
    "Bioluminescent Jellyfish": "",
    "Depth Stalker": "",
    "Abyssal Serpent": "",
    "Trench Golem": "",
    "Darkness Whale": "",
    "Storm Eagle": "",
    "Cloud Serpent": "",
    "Thunder Elk": "",
    "Sky Leviathan": "",
    "Divine Wolf": "",
    "Astral Panther": "",
    "Heavenly Dragon": "",
    "Celestial Bear": "",
    "Void Phoenix": "",
    "The Eternal Hunter": ""
  },
  "biomes": {
    "Village": "",
    "Forest": "",
    "Woods": "",
    "Small Desert": "",
    "Large Desert": "",
    "Tundra": "",
    "Jungle": "",
    "Swamp": "",
    "Volcanic Highlands": "",
    "Cursed Ruins": "",
    "Rainbow Realm": "",
    "Abyssal Depths": "",
    "Celestial Peaks": ""
  },
  "weapons": {
    "Bare Hands": "",
    "Slingshot": "",
    "Hunting Knife": "",
    "Spear": "",
    "Shortbow": "",
    "Longbow": "",
    "Crossbow": "",
    "Musket": "",
    "Hunting Rifle": "",
    "Shotgun": "",
    "Sniper Rifle": "",
    "Tranq Gun": "",
    "Plasma Caster": "",
    "Gravity Trap": "",
    "Soul Snare": "",
    "Void Bow": "",
    "Celestial Lance": "",
    "Mythic Net": "",
    "Dragon Cannon": "",
    "Cosmic RPG": "",
    "Nuke Launcher": ""
  },
  "ammo": {
    "Wooden Arrow": "",
    "Iron Arrow": "",
    "Enchanted Arrow": "",
    "Phantom Arrow": "",
    "Crude Bolt": "",
    "Steel Bolt": "",
    "Gilded Bolt": "",
    "Venom Bolt": "",
    "Lead Ball": "",
    "Hollow Point": "",
    "Silver Bullet": "",
    "Void Round": "",
    "Basic Tranq": "",
    "Potent Tranq": "",
    "Exotic Serum": "",
    "Void Serum": "",
    "Charged Cell": "",
    "Overcharged Cell": "",
    "Plasma Core": "",
    "Singularity Cell": "",
    "Fractured Shard": "",
    "Pure Shard": "",
    "Void Shard": "",
    "Eternal Shard": "",
    "Star Slug": "",
    "Nebula Round": "",
    "Celestial Core": "",
    "Eternal Cosmos": "",
    "Nuke": ""
  }
};
