window.IDLE_HUNTER_IMAGES = {
  "animals": {
    "Rat": "",
    "Mouse": "",
    "Stray Cat": "",
    "Pigeon": "",
    "Crow": "",
    "Rabbit": "",
    "Fox": "",
    "Stray Dog": "",
    "Squirrel": "",
    "Sparrow": "",
    "Deer": "",
    "Wild Boar": "",
    "Wolf": "",
    "Bear": "",
    "Elk": "",
    "Lynx": "",
    "Badger": "",
    "Pheasant": "",
    "Owl": "",
    "Hare": "",
    "Moose": "",
    "Timber Wolf": "",
    "Black Bear": "",
    "Wild Turkey": "",
    "Coyote": "",
    "Raccoon": "",
    "Porcupine": "",
    "Snapping Turtle": "",
    "Grouse": "",
    "Mink": "",
    "Scorpion": "",
    "Sand Viper": "",
    "Vulture": "",
    "Fennec Fox": "",
    "Armadillo": "",
    "Roadrunner": "",
    "Lizard": "",
    "Camel Spider": "",
    "Jerboa": "",
    "Sandstorm Serpent": "",
    "Desert Lion": "",
    "Giant Scorpion": "",
    "Dust Hyena": "",
    "Sand Golem Crab": "",
    "Camel": "",
    "Dune Stalker Wolf": "",
    "Golden Eagle": "",
    "Desert Lynx": "",
    "Mirage Phantom": "",
    "Arctic Wolf": "",
    "Polar Bear": "",
    "Snowy Owl": "",
    "Reindeer": "",
    "Arctic Fox": "",
    "Musk Ox": "",
    "Wolverine": "",
    "Seal": "",
    "Walrus": "",
    "Snow Leopard": "",
    "Jaguar": "",
    "Anaconda": "",
    "Poison Dart Frog": "",
    "Toucan": "",
    "Panther": "",
    "Silverback Gorilla": "",
    "Komodo Dragon": "",
    "Piranha": "",
    "Giant Centipede": "",
    "Alligator": "",
    "Giant Frog": "",
    "Swamp Viper": "",
    "Mudskipper": "",
    "Black Panther": "",
    "Leech Hydra": "",
    "Bog Bear": "",
    "Marsh Hawk": "",
    "Will-o-Wisp Serpent": "",
    "Lava Lizard": "",
    "Magma Boar": "",
    "Ember Wolf": "",
    "Ash Vulture": "",
    "Cinder Crab": "",
    "Obsidian Serpent": "",
    "Flame Lynx": "",
    "Molten Golem": "",
    "Fire Hawk": "",
    "Inferno Bear": "",
    "Skeleton Archer": "",
    "Shadow Wolf": "",
    "Bone Drake": "",
    "Cursed Knight": "",
    "Wraith Stag": "",
    "Plague Rat": "",
    "Stone Golem": "",
    "Phantom Lynx": "",
    "Soul Serpent": "",
    "Ancient Guardian": "",
    "Prismatic Butterfly": "",
    "Chromatic Fox": "",
    "Rainbow Serpent": "",
    "Aurora Deer": "",
    "Spectrum Wolf": "",
    "Iridescent Hawk": "",
    "Prism Panther": "",
    "Hue Shifter Frog": "",
    "Kaleidoscope Crab": "",
    "The Living Rainbow": "",
    "Deep Sea Kraken": "",
    "Abyss Shark": "",
    "Shadow Eel": "",
    "Void Manta": "",
    "Leviathan Crab": "",
    "Bioluminescent Jellyfish": "",
    "Depth Stalker": "",
    "Abyssal Serpent": "",
    "Trench Golem": "",
    "Darkness Whale": "",
    "Storm Eagle": "",
    "Cloud Serpent": "",
    "Thunder Elk": "",
    "Sky Leviathan": "",
    "Divine Wolf": "",
    "Astral Panther": "",
    "Heavenly Dragon": "",
    "Celestial Bear": "",
    "Void Phoenix": "",
    "The Eternal Hunter": ""
  },
  "biomes": {
    "Village": "assets/biomes/village.png",
    "Forest": "assets/biomes/forest.png",
    "Woods": "assets/biomes/woods.png",
    "Small Desert": "assets/biomes/small_desert.png",
    "Large Desert": "assets/biomes/large_desert.png",
    "Tundra": "assets/biomes/tundra.png",
    "Jungle": "assets/biomes/jungle.png",
    "Swamp": "assets/biomes/swamp.png",
    "Volcanic Highlands": "assets/biomes/volcanic_highlands.png",
    "Cursed Ruins": "assets/biomes/cursed_ruins.png",
    "Rainbow Realm": "assets/biomes/rainbow.png",
    "Abyssal Depths": "assets/biomes/abyssal_depths.png",
    "Celestial Peaks": "assets/biomes/celestial_peaks.png"
  },
  "weapons": {
    "Bare Hands": "assets/weapons/bare-hands.png",
    "Slingshot": "assets/weapons/slingshot.png",
    "Hunting Knife": "assets/weapons/hunting-knife.png",
    "Spear": "assets/weapons/spear.png",
    "Shortbow": "assets/weapons/shortbow.png",
    "Longbow": "assets/weapons/longbow.png",
    "Crossbow": "assets/weapons/crossbow.png",
    "Musket": "assets/weapons/musket.png",
    "Hunting Rifle": "assets/weapons/hunting-rifle.png",
    "Shotgun": "assets/weapons/shotgun.png",
    "Sniper Rifle": "assets/weapons/sniper-rifle.png",
    "Tranq Gun": "assets/weapons/tranq-gun.png",
    "Plasma Caster": "assets/weapons/plasma-caster.png",
    "Gravity Trap": "assets/weapons/gravity-trap.png",
    "Soul Snare": "assets/weapons/soul-snare.png",
    "Void Bow": "assets/weapons/void-bow.png",
    "Celestial Lance": "assets/weapons/celestial-lance.png",
    "Mythic Net": "assets/weapons/mythic-net.png",
    "Dragon Cannon": "assets/weapons/dragon-cannon.png",
    "Cosmic RPG": "assets/weapons/cosmic-rpg.png",
    "Nuke Launcher": "assets/weapons/nuke-launcher.png"
  },
  "ammo": {
    "Wooden Arrow": "assets/ammo/wooden-arrow.png",
    "Iron Arrow": "assets/ammo/iron-arrow.png",
    "Enchanted Arrow": "assets/ammo/enchanted-arrow.png",
    "Phantom Arrow": "assets/ammo/phantom-arrow.png",
    "Crude Bolt": "assets/ammo/crude-bolt.png",
    "Steel Bolt": "assets/ammo/steel-bolt.png",
    "Gilded Bolt": "assets/ammo/gilded-bolt.png",
    "Venom Bolt": "assets/ammo/venom-bolt.png",
    "Lead Ball": "assets/ammo/lead-ball.png",
    "Hollow Point": "assets/ammo/hollow-point.png",
    "Silver Bullet": "assets/ammo/silver-bullet.png",
    "Void Round": "assets/ammo/void-round.png",
    "Basic Tranq": "assets/ammo/basic-tranq.png",
    "Potent Tranq": "assets/ammo/potent-tranq.png",
    "Exotic Serum": "assets/ammo/exotic-serum.png",
    "Void Serum": "assets/ammo/void-serum.png",
    "Charged Cell": "assets/ammo/charged-cell.png",
    "Overcharged Cell": "assets/ammo/overcharged-cell.png",
    "Plasma Core": "assets/ammo/plasma-core.png",
    "Singularity Cell": "assets/ammo/singularity-cell.png",
    "Fractured Shard": "assets/ammo/fractured-shard.png",
    "Pure Shard": "assets/ammo/pure-shard.png",
    "Void Shard": "assets/ammo/void-shard.png",
    "Eternal Shard": "assets/ammo/eternal-shard.png",
    "Star Slug": "assets/ammo/star-slug.png",
    "Nebula Round": "assets/ammo/nebula-round.png",
    "Celestial Core": "assets/ammo/celestial-core.png",
    "Eternal Cosmos": "assets/ammo/eternal-cosmos.png",
    "Nuke": "assets/ammo/nuke.png"
  }
};
